using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Net.Http.Json;
using System.Text.Json;
using System.Threading.Tasks;
using SystemCtrl.Core.Interfaces;
using SystemCtrl.Core.Models;

namespace SystemCtrl.Core;

public class ServiceAnalyzer : IServiceAnalyzer
{
    private readonly HttpClient _httpClient;
    private readonly ISettingsService _settingsService;

    public ServiceAnalyzer(HttpClient httpClient, ISettingsService settingsService)
    {
        _httpClient = httpClient ?? throw new ArgumentNullException(nameof(httpClient));
        _settingsService = settingsService ?? throw new ArgumentNullException(nameof(settingsService));
    }

    public async Task<List<AiQna>> AnalyzeServiceAsync(DetailedWindowsServiceInfo serviceInfo)
    {
        if (serviceInfo == null)
            throw new ArgumentNullException(nameof(serviceInfo));

        var settings = _settingsService.LoadSettings();
        if (string.IsNullOrWhiteSpace(settings.GeminiApiKey))
        {
            return new List<AiQna> { new AiQna { Question = "Error", Answer = "API Key is missing. Please configure your Gemini API Key in the settings." } };
        }

        var prompt = $"Please analyze the following Windows Service. Answer the following 3 questions:\n" +
                     $"1. What does this service do?\n" +
                     $"2. Is it critical for the system?\n" +
                     $"3. Is it safe to disable?\n\n" +
                     $"Return the response STRICTLY as a JSON array of objects, where each object has a 'Question' and 'Answer' property. " +
                     $"Do NOT use any markdown formatting (no bold, no asterisks, no code blocks). Keep the answers short and concise.\n\n" +
                     $"Service Name: {serviceInfo.ServiceName}\n" +
                     $"Executable Path: {serviceInfo.ExecutablePath}\n" +
                     $"Executable Name: {serviceInfo.ExecutableName}\n" +
                     $"Publisher: {serviceInfo.Publisher}\n" +
                     $"Is Signed: {serviceInfo.IsSigned}\n" +
                     $"Service Account: {serviceInfo.ServiceAccount}\n" +
                     $"Dependencies: {(serviceInfo.Dependencies != null && serviceInfo.Dependencies.Length > 0 ? string.Join(", ", serviceInfo.Dependencies) : "None")}\n";

        var requestBody = new
        {
            contents = new[]
            {
                new
                {
                    parts = new[]
                    {
                        new { text = prompt }
                    }
                }
            }
        };

        var modelName = string.IsNullOrWhiteSpace(settings.GeminiModel) 
            ? "gemini-1.5-flash" 
            : settings.GeminiModel;

        var url = $"https://generativelanguage.googleapis.com/v1beta/models/{modelName}:generateContent?key={settings.GeminiApiKey}";
        
        try
        {
            var response = await _httpClient.PostAsJsonAsync(url, requestBody);
            
            if (!response.IsSuccessStatusCode)
            {
                var error = await response.Content.ReadAsStringAsync();
                return new List<AiQna> { new AiQna { Question = "Error", Answer = $"Error from AI service: {response.StatusCode} - {response.ReasonPhrase}\n{error}" } };
            }
            
            var jsonResponse = await response.Content.ReadAsStringAsync();
            using var document = JsonDocument.Parse(jsonResponse);
            
            var text = document.RootElement
                .GetProperty("candidates")[0]
                .GetProperty("content")
                .GetProperty("parts")[0]
                .GetProperty("text")
                .GetString();

            if (string.IsNullOrWhiteSpace(text))
            {
                return new List<AiQna> { new AiQna { Question = "Error", Answer = "No analysis generated by the AI." } };
            }

            // Remove markdown code block if the AI returned it despite instructions
            text = text.Trim();
            if (text.StartsWith("```json"))
            {
                text = text.Substring(7);
                if (text.EndsWith("```"))
                {
                    text = text.Substring(0, text.Length - 3);
                }
            }
            else if (text.StartsWith("```"))
            {
                text = text.Substring(3);
                if (text.EndsWith("```"))
                {
                    text = text.Substring(0, text.Length - 3);
                }
            }

            var options = new JsonSerializerOptions { PropertyNameCaseInsensitive = true };
            var result = JsonSerializer.Deserialize<List<AiQna>>(text, options);

            return result ?? new List<AiQna> { new AiQna { Question = "Error", Answer = "Failed to parse AI response." } };
        }
        catch (Exception ex)
        {
            return new List<AiQna> { new AiQna { Question = "Error", Answer = $"Failed to analyze service. Error: {ex.Message}" } };
        }
    }
}
