using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Net.Http.Json;
using System.Text.Json;
using System.Threading.Tasks;
using SystemCtrl.Core.Interfaces;
using SystemCtrl.Core.Models;

namespace SystemCtrl.Core;

public class ServiceAnalyzer(HttpClient httpClient) : IServiceAnalyzer
{
    private readonly HttpClient _httpClient = httpClient ?? throw new ArgumentNullException(nameof(httpClient));

    public async Task<List<AiQna>> AnalyzeServiceAsync(DetailedWindowsServiceInfo serviceInfo, AppSettings settings)
    {
        ArgumentNullException.ThrowIfNull(serviceInfo);
        ArgumentNullException.ThrowIfNull(settings);
        
        if (string.IsNullOrWhiteSpace(settings.GeminiApiKey))
        {
            return
            [
                new AiQna
                {
                    Question = "Error",
                    Answer = "API Key is missing. Please configure your Gemini API Key in the settings."
                }
            ];
        }

        var prompt = $"Please analyze the following Windows Service. Answer the following 3 questions:\n" +
                     $"1. What does this service do?\n" +
                     $"2. Is it critical for the system?\n" +
                     $"3. Is it safe to disable?\n\n" +
                     $"Return the response STRICTLY as a JSON array of objects, where each object has a 'Question' and 'Answer' property. " +
                     $"Do NOT use any markdown formatting (no bold, no asterisks, no code blocks). Keep the answers short and concise.\n\n" +
                     $"Service Name: {serviceInfo.ServiceName}\n" +
                     $"Executable Path: {serviceInfo.ExecutablePath}\n" +
                     $"Executable Name: {serviceInfo.ExecutableName}\n" +
                     $"Publisher: {serviceInfo.Publisher}\n" +
                     $"Is Signed: {serviceInfo.IsSigned}\n" +
                     $"Service Account: {serviceInfo.ServiceAccount}\n" +
                     $"Dependencies: {(serviceInfo.Dependencies.Length > 0 ? string.Join(", ", serviceInfo.Dependencies) : "None")}\n";

        var requestBody = new
        {
            contents = new[]
            {
                new
                {
                    parts = new[]
                    {
                        new { text = prompt }
                    }
                }
            }
        };

        var modelName = string.IsNullOrWhiteSpace(settings.GeminiModel) 
            ? "gemini-1.5-flash" 
            : settings.GeminiModel;

        var url = $"https://generativelanguage.googleapis.com/v1beta/models/{modelName}:generateContent?key={settings.GeminiApiKey}";

        var options = new JsonSerializerOptions { PropertyNameCaseInsensitive = true };
        try
        {
            var response = await _httpClient.PostAsJsonAsync(url, requestBody);
            
            if (!response.IsSuccessStatusCode)
            {
                var error = await response.Content.ReadAsStringAsync();
                return new List<AiQna> { new AiQna { Question = "Error", Answer = $"Error from AI service: {response.StatusCode} - {response.ReasonPhrase}\n{error}" } };
            }
            
            var jsonResponse = await response.Content.ReadAsStringAsync();
            using var document = JsonDocument.Parse(jsonResponse);
            
            var text = document.RootElement
                .GetProperty("candidates")[0]
                .GetProperty("content")
                .GetProperty("parts")[0]
                .GetProperty("text")
                .GetString();

            if (string.IsNullOrWhiteSpace(text))
            {
                return [new AiQna { Question = "Error", Answer = "No analysis generated by the AI." }];
            }

            text = text.Trim();
            if (text.StartsWith("```json"))
            {
                text = text[7..];
                if (text.EndsWith("```"))
                {
                    text = text[..^3];
                }
            }
            else if (text.StartsWith("```"))
            {
                text = text[3..];
                if (text.EndsWith("```"))
                {
                    text = text[..^3];
                }
            }

            var result = JsonSerializer.Deserialize<List<AiQna>>(text, options);

            return result ?? [new AiQna() { Question = "Error", Answer = "Failed to parse AI response." }];
        }
        catch (Exception ex)
        {
            return [new AiQna() { Question = "Error", Answer = $"Failed to analyze service. Error: {ex.Message}" }];
        }
    }
}
