using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Net.Http.Json;
using System.Text.Json;
using System.Threading.Tasks;
using SystemCtrl.Core.Interfaces;
using SystemCtrl.Core.Models;

namespace SystemCtrl.Core;

public class ServiceAnalyzer : IServiceAnalyzer
{
    private readonly HttpClient _httpClient;
    private readonly ISettingsService _settingsService;

    public ServiceAnalyzer(HttpClient httpClient, ISettingsService settingsService)
    {
        _httpClient = httpClient ?? throw new ArgumentNullException(nameof(httpClient));
        _settingsService = settingsService ?? throw new ArgumentNullException(nameof(settingsService));
    }

    public async Task<string> AnalyzeServiceAsync(DetailedWindowsServiceInfo serviceInfo)
    {
        if (serviceInfo == null)
            throw new ArgumentNullException(nameof(serviceInfo));

        var settings = _settingsService.LoadSettings();
        if (string.IsNullOrWhiteSpace(settings.GeminiApiKey))
        {
            return "API Key is missing. Please configure your Gemini API Key in the settings.";
        }

        var prompt = $"Please analyze the following Windows Service and summarize what it does in a concise manner. " +
                     $"Mention if it is a critical system service, its typical use cases, and whether it is generally safe to disable.\n\n" +
                     $"Service Name: {serviceInfo.ServiceName}\n" +
                     $"Executable Path: {serviceInfo.ExecutablePath}\n" +
                     $"Executable Name: {serviceInfo.ExecutableName}\n" +
                     $"Publisher: {serviceInfo.Publisher}\n" +
                     $"Is Signed: {serviceInfo.IsSigned}\n" +
                     $"Service Account: {serviceInfo.ServiceAccount}\n" +
                     $"Dependencies: {(serviceInfo.Dependencies != null && serviceInfo.Dependencies.Length > 0 ? string.Join(", ", serviceInfo.Dependencies) : "None")}\n";

        var requestBody = new
        {
            contents = new[]
            {
                new
                {
                    parts = new[]
                    {
                        new { text = prompt }
                    }
                }
            }
        };

        var modelName = string.IsNullOrWhiteSpace(settings.GeminiModel) 
            ? "gemini-1.5-flash" 
            : settings.GeminiModel;

        var url = $"https://generativelanguage.googleapis.com/v1beta/models/{modelName}:generateContent?key={settings.GeminiApiKey}";
        
        try
        {
            var response = await _httpClient.PostAsJsonAsync(url, requestBody);
            
            if (!response.IsSuccessStatusCode)
            {
                var error = await response.Content.ReadAsStringAsync();
                return $"Error from AI service: {response.StatusCode} - {response.ReasonPhrase}\n{error}";
            }
            
            var jsonResponse = await response.Content.ReadAsStringAsync();
            using var document = JsonDocument.Parse(jsonResponse);
            
            var text = document.RootElement
                .GetProperty("candidates")[0]
                .GetProperty("content")
                .GetProperty("parts")[0]
                .GetProperty("text")
                .GetString();

            return text?.Trim() ?? "No analysis generated by the AI.";
        }
        catch (Exception ex)
        {
            return $"Failed to analyze service. Error: {ex.Message}";
        }
    }
}
